### ISSUE TITLE
Aspect ratio philosophy

### ISSUE THREAD

**Issue by mdings** [maximelebreton/sass-modern-mq#3]
Hey I like the rationale behind your approach. I do wonder how you would approach the following scenario though. Let's assume I have a widget that displays elements next to each other.

- In portrait mode on a phone I would want to show the elements underneath each other
- In portrait mode on an iPad Pro I have more real estate so multiple elements would fit next to each other.

If I use the portrait breakpoint then they would also stack on top of each other on devices where we have more room to display a grid.

How do you see this?

**Comment by maximelebreton** [comment]
hello @mdings, sorry for the laaaate response!

For this scenario, you can combine `portrait` and `width` queries: 
- https://github.com/maximelebreton/sass-modern-mq#usage
- https://github.com/maximelebreton/sass-modern-mq#optional-breakpoints-width-height-and-retina

```scss
.your-widget {
  @include mq("portrait and width<=small") {
    // phone
    flex-direction: row;
  }
  @include mq("portrait and width>small") {
    // tablet
    flex-direction: column;
  }
}
```
